### ISSUE TITLE
Audio anthology?

### ISSUE THREAD

**Issue by lnewportmsft** [MilesRomney/MechMuse#1]
I realize this is super unorthodox - but I can't get in touch via the email on your mechmuse site.  :)

Do you, or do you know of anyone who has the old audio from the MechMuse Audio Anthology? Specifically I'm looking for the rest of "On My Way to Paradise..." .

Thank you!

**Comment by MilesRomney** [comment]
Hey, no problem at all. It happens I'm acquainted with the audio anthology. :)

Alas, it was before its time. If it had come now, during the podcast surge, it would be a going concern. But at the time, the idea of listening to short-form audio on a portable player was just too novel. On My Way to Paradise was planned to span 4 issues, and only 2 were produced. So there is no audio conclusion from MechMuse (or anyone else that I'm aware of).

The good news, though, is that Bantom has [re-released it in paperback and eBook](https://www.amazon.com/My-Way-Paradise-David-Farland-ebook/dp/B0037UY510/ref=sr_1_1?keywords=on+my+way+to+paradise&qid=1575419580&sr=8-1).

Happy reading!
